language: node_js
node_js:
  - '6'
  - '8'
  - '10'
  - '11'
after_success:
  - hash npx 2> /dev/null && npx codecov
deploy:
  provider: npm
  email: remcohaszing@gmail.com
  api_key: $NPM_ACCESS_TOKEN
  on:
    tags: true
    node: '10'
